import Foundation
import XCTest

@testable import FluidAudio

final class ChatterboxTokenizerTests: XCTestCase {

    private var tmpDir: URL!

    override func setUpWithError() throws {
        try super.setUpWithError()
        tmpDir = FileManager.default.temporaryDirectory
            .appendingPathComponent("ChatterboxTokenizerTests-\(UUID().uuidString)")
        try FileManager.default.createDirectory(at: tmpDir, withIntermediateDirectories: true)
    }

    override func tearDownWithError() throws {
        if let tmpDir, FileManager.default.fileExists(atPath: tmpDir.path) {
            try FileManager.default.removeItem(at: tmpDir)
        }
        try super.tearDownWithError()
    }

    // MARK: - Decomposed characters (fixture vocab, non-skipping)

    /// After NFKD, "ü" is the two scalars `u` + U+0308 but ONE Swift
    /// Character; the BPE must iterate scalars or every accented character
    /// collapses to [UNK]. Fixture vocabulary deliberately has no
    /// precomposed entries, so grapheme-cluster iteration cannot pass.
    func testDecomposedCharactersTokenizePerScalar() throws {
        let json = """
            {
              "model": {
                "vocab": {"[UNK]": 0, "u": 10, "\\u0308": 11, "b": 12, "e": 13, "r": 14},
                "merges": []
              },
              "added_tokens": [
                {"content": "[de]", "id": 100},
                {"content": "[SPACE]", "id": 101}
              ]
            }
            """
        let url = tmpDir.appendingPathComponent("tokenizer.json")
        try json.data(using: .utf8)!.write(to: url)
        let tokenizer = try ChatterboxTokenizer(tokenizerJsonURL: url)

        let ids = tokenizer.encode("über", languageId: "de")
        XCTAssertEqual(ids, [100, 10, 11, 12, 13, 14])
        XCTAssertFalse(ids.dropFirst().contains(0), "accented char fell to [UNK]")
    }

    // MARK: - puncNorm

    func testPuncNormCollapsesAllWhitespace() {
        // Python str.split() collapses tabs and newlines, not just spaces.
        XCTAssertEqual(
            ChatterboxTokenizer.puncNorm("Hello\nworld\tagain"), "Hello world again.")
        XCTAssertEqual(
            ChatterboxTokenizer.puncNorm("Line one.\n\nLine two."), "Line one. Line two.")
    }

    func testPuncNormAddsTrailingStopAndCapitalizes() {
        XCTAssertEqual(ChatterboxTokenizer.puncNorm("hello world"), "Hello world.")
        XCTAssertEqual(ChatterboxTokenizer.puncNorm("Done!"), "Done!")
        XCTAssertEqual(
            ChatterboxTokenizer.puncNorm(""),
            "You need to add some text for me to talk.")
    }

    func testPuncNormReplacesLlmPunctuation() {
        // Upstream collapses whitespace BEFORE the punctuation replacements,
        // so ", " insertions legitimately produce double spaces — verified
        // against the Python reference (and the [7,2,2] double-SPACE ids in
        // the parity vectors below).
        XCTAssertEqual(
            ChatterboxTokenizer.puncNorm("wait; ok… fine — yes"),
            "Wait,  ok,  fine - yes.")
        XCTAssertEqual(ChatterboxTokenizer.puncNorm("a  b   c"), "A b c.")
    }

    // MARK: - Mechanics on a small synthetic vocab

    private func makeTinyTokenizer() throws -> ChatterboxTokenizer {
        let json: [String: Any] = [
            "added_tokens": [
                ["id": 2, "content": "[SPACE]"],
                ["id": 100, "content": "[en]"],
            ],
            "model": [
                "type": "BPE",
                "vocab": [
                    "[UNK]": 1, "a": 10, "b": 11, "c": 12, "ab": 20, "abc": 21, ".": 30,
                ],
                "merges": ["a b", "ab c"],
            ],
        ]
        let url = tmpDir.appendingPathComponent("tiny.json")
        try JSONSerialization.data(withJSONObject: json).write(to: url)
        return try ChatterboxTokenizer(tokenizerJsonURL: url)
    }

    func testAddedTokenSplitAndBpeMergeOrder() throws {
        let tokenizer = try makeTinyTokenizer()
        // "[en]" prefix + "abc ab." → added(100), abc→21, SPACE(2), ab→20, .→30
        XCTAssertEqual(tokenizer.encode("abc ab.", languageId: "en"), [100, 21, 2, 20, 30])
    }

    func testUnknownCharactersMapToUnk() throws {
        let tokenizer = try makeTinyTokenizer()
        XCTAssertEqual(tokenizer.encode("q", languageId: "en"), [100, 1])
    }

    // MARK: - Parity vectors against the real vocab (skips without the asset)

    /// Generated by the mobius reference tokenizer
    /// (`models/tts/chatterbox/coreml`, MTLTokenizer + punc_norm).
    private static let vectors: [(String, String, [Int])] = [
        (
            "en", "The quick brown fox jumps over the lazy dog near the river bank.",
            [
                708, 42, 2, 194, 91, 24, 2, 243, 190, 2, 182, 37, 2, 23, 231, 29, 32, 2, 253,
                2, 42, 2, 25, 14, 39, 38, 2, 134, 20, 2, 111, 59, 2, 42, 2, 101, 90, 2, 15,
                43, 24, 9,
            ]
        ),
        (
            "de", "Der schnelle braune Fuchs springt über den faulen Hund am Flussufer.",
            [
                636, 234, 2, 32, 71, 111, 25, 64, 2, 243, 14, 97, 18, 2, 19, 34, 71, 32, 2,
                248, 31, 52, 33, 2, 34, 762, 15, 44, 2, 17, 50, 2, 19, 14, 167, 50, 2, 21, 97,
                17, 2, 122, 2, 19, 25, 142, 133, 19, 44, 9,
            ]
        ),
        (
            "fr", "Le renard brun rapide saute par-dessus le chien paresseux près de la rivière.",
            [
                634, 64, 2, 46, 27, 177, 2, 243, 97, 2, 31, 155, 208, 2, 150, 96, 18, 2, 29,
                59, 8, 17, 61, 133, 32, 2, 64, 2, 71, 22, 50, 2, 29, 127, 32, 66, 34, 37, 2,
                29, 46, 768, 32, 2, 126, 2, 25, 14, 2, 101, 35, 236, 768, 46, 9,
            ]
        ),
        (
            "es", "Hola, ¿cómo estás? Bien.",
            [635, 21, 28, 25, 14, 7, 2, 360, 174, 764, 115, 2, 218, 14, 764, 32, 13, 2, 15, 22, 50, 9]
        ),
        (
            "en", "Dr. Smith paid $5 – no, wait; $6... (roughly)!",
            [
                708, 17, 31, 9, 2, 32, 26, 22, 40, 2, 29, 14, 83, 2, 258, 268, 2, 8, 2, 95, 7,
                2, 36, 14, 60, 7, 2, 2, 258, 269, 7, 2, 2, 5, 31, 202, 70, 6, 3,
            ]
        ),
    ]

    func testRealVocabParityVectors() throws {
        let cached = try? TtsCacheDirectory.ensure()
            .appendingPathComponent("Models")
            .appendingPathComponent(Repo.chatterbox.folderName)
            .appendingPathComponent(ModelNames.Chatterbox.tokenizerFile)
        guard let cached, FileManager.default.fileExists(atPath: cached.path) else {
            throw XCTSkip("Chatterbox tokenizer asset not downloaded")
        }
        let tokenizer = try ChatterboxTokenizer(tokenizerJsonURL: cached)
        for (lang, text, expected) in Self.vectors {
            let normalized = ChatterboxTokenizer.puncNorm(text)
            XCTAssertEqual(
                tokenizer.encode(normalized, languageId: lang), expected,
                "mismatch for \(lang): \(text)")
        }
    }
}
